# data.py
# Diccionarios de países e idiomas.
# Guardar como data.py

PAISES_DISPONIBLES = {
    "Angola (AGO)": "AGO",
    "Arabia Saudita (ARE)": "ARE",
    "Argentina (ARG)": "ARG",
    "Australia (AUS)": "AUS",
    "Austria (AUT)": "AUT",
    "Azerbaiyán (AZE)": "AZE",
    "Bélgica (BEL)": "BEL",
    "Bangladesh (BGD)": "BGD",
    "Bulgaria (BGR)": "BGR",
    "Bahrein (BHR)": "BHR",
    "Bosnia y Herzegovina (BIH)": "BIH",
    "Bielorrusia (BLR)": "BLR",
    "Bermudas (BMU)": "BMU",
    "Bolivia (BOL)": "BOL",
    "Brasil (BRA)": "BRA",
    "Botswana (BWA)": "BWA",
    "Canadá (CAN)": "CAN",
    "Suiza (CHE)": "CHE",
    "Chile (CHL)": "CHL",
    "China (CHN)": "CHN",
    "Camerún (CMR)": "CMR",
    "Rep. Democrática del Congo (COD)": "COD",
    "Congo (COG)": "COG",
    "Colombia (COL)": "COL",
    "Costa Rica (CRI)": "CRI",
    "Chipre (CYP)": "CYP",
    "Chequia (CZE)": "CZE",
    "Alemania (DEU)": "DEU",
    "República Dominicana (DOM)": "DOM",
    "Dinamarca (DNK)": "DNK",
    "Ecuador (ECU)": "ECU",
    "Egipto (EGY)": "EGY",
    "España (ESP)": "ESP",
    "Estonia (EST)": "EST",
    "Etiopía (ETH)": "ETH",
    "Finlandia (FIN)": "FIN",
    "Francia (FRA)": "FRA",
    "Gabón (GAB)": "GAB",
    "Reino Unido (GBR)": "GBR",
    "Georgia (GEO)": "GEO",
    "Guernesey (GGY)": "GGY",
    "Ghana (GHA)": "GHA",
    "Grecia (GRC)": "GRC",
    "Guatemala (GTM)": "GTM",
    "Hong Kong (HKG)": "HKG",
    "Honduras (HND)": "HND",
    "Croacia (HRV)": "HRV",
    "Hungría (HUN)": "HUN",
    "Indonesia (IDN)": "IDN",
    "Isla de Man (IMN)": "IMN",
    "India (IND)": "IND",
    "Irlanda (IRL)": "IRL",
    "Irán (IRN)": "IRN",
    "Irak (IRQ)": "IRQ",
    "Islandia (ISL)": "ISL",
    "Israel (ISR)": "ISR",
    "Italia (ITA)": "ITA",
    "Jersey (JEY)": "JEY",
    "Jordania (JOR)": "JOR",
    "Japón (JPN)": "JPN",
    "Kazajistán (KAZ)": "KAZ",
    "Kenia (KEN)": "KEN",
    "Kirguistán (KGZ)": "KGZ",
    "Camboya (KHM)": "KHM",
    "Corea del Sur (KOR)": "KOR",
    "Kuwait (KWT)": "KWT",
    "Líbano (LBN)": "LBN",
    "Sri Lanka (LKA)": "LKA",
    "Lesoto (LSO)": "LSO",
    "Lituania (LTU)": "LTU",
    "Luxemburgo (LUX)": "LUX",
    "Letonia (LVA)": "LVA",
    "Marruecos (MAR)": "MAR",
    "México (MEX)": "MEX",
    "Macedonia (MKD)": "MKD",
    "Malta (MLT)": "MLT",
    "Myanmar (MMR)": "MMR",
    "Mozambique (MOZ)": "MOZ",
    "Mauricio (MUS)": "MUS",
    "Malawi (MWI)": "MWI",
    "Malasia (MYS)": "MYS",
    "Namibia (NAM)": "NAM",
    "Nicaragua (NIC)": "NIC",
    "Nueva Caledonia (NCL)": "NCL",
    "Nigeria (NGA)": "NGA",
    "Países Bajos (NLD)": "NLD",
    "Noruega (NOR)": "NOR",
    "Nueva Zelanda (NZL)": "NZL",
    "Omán (OMN)": "OMN",
    "Panamá (PAN)": "PAN",
    "Pakistán (PAK)": "PAK",
    "Perú (PER)": "PER",
    "Filipinas (PHL)": "PHL",
    "Polonia (POL)": "POL",
    "Puerto Rico (PRI)": "PRI",
    "Portugal (PRT)": "PRT",
    "Paraguay (PRY)": "PRY",
    "Catar (QAT)": "QAT",
    "Rumania (ROU)": "ROU",
    "Rusia (RUS)": "RUS",
    "Singapur (SGP)": "SGP",
    "El Salvador (SLV)": "SLV",
    "Serbia (SRB)": "SRB",
    "Sudán del Sur (SSD)": "SSD",
    "Surinam (SUR)": "SUR",
    "Eslovaquia (SVK)": "SVK",
    "Eslovenia (SVN)": "SVN",
    "Suecia (SWE)": "SWE",
    "Swazilandia (SWZ)": "SWZ",
    "Chad (TCD)": "TCD",
    "Tailandia (THA)": "THA",
    "Túnez (TUN)": "TUN",
    "Turquía (TUR)": "TUR",
    "Taiwán (TWN)": "TWN",
    "Tanzania (TZA)": "TZA",
    "Uganda (UGA)": "UGA",
    "Ucrania (UKR)": "UKR",
    "Uruguay (URY)": "URY",
    "Venezuela (VEN)": "VEN",
    "Islas Vírgenes (VIR)": "VIR",
    "Vietnam (VNM)": "VNM",
    "Kosovo (XKX)": "XKX",
    "Sudáfrica (ZAF)": "ZAF",
    "Zambia (ZMB)": "ZMB",
    "Zimbabue (ZWE)": "ZWE",
    "Estados Unidos (USA)": "USA"
}

IDIOMAS_DISPONIBLES = {
    "Árabe (Arabia Saudita)": "ar-SA",
    "Búlgaro (Bulgaria)": "bg-BG",
    "Bosnio (Bosnia y Herzegovina)": "bs-BS",
    "Bosnio (Indonesia)": "bs-ID",
    "Catalán (España)": "ca-ES",
    "Montenegrino (Montenegro)": "cnr-ME",
    "Checo (República Checa)": "cs-CZ",
    "Galés (Reino Unido)": "cy-GB",
    "Danés (Dinamarca)": "da-DK",
    "Alemán (Suiza)": "de-CH",
    "Alemán (Alemania)": "de-DE",
    "Griego (Grecia)": "el-GR",
    "Inglés (Reino Unido)": "en-GB",
    "Inglés (DEBUG)": "en-DEBUG",
    "Español (España)": "es-ES",
    "Español (México)": "es-MX",
    "Estonio (Estonia)": "et-EE",
    "Finlandés (Finlandia)": "fi-FI",
    "Francés (Canadá)": "fr-CA",
    "Francés (Francia)": "fr-FR",
    "Hebreo (Israel)": "he-IL",
    "Hindi (India)": "hi-IN",
    "Croata (Croacia)": "hr-HR",
    "Húngaro (Hungría)": "hu-HU",
    "Italiano (Italia)": "it-IT",
    "Japonés (Japón)": "ja-JP",
    "Coreano (Corea del Sur)": "ko-KR",
    "Lituano (Lituania)": "lt-LT",
    "Letón (Letonia)": "lv-LV",
    "Macedonio (Macedonia)": "mk-MK",
    "Noruego (Noruega)": "nb-NO",
    "Neerlandés (Países Bajos)": "nl-NL",
    "Polaco (Polonia)": "pl-PL",
    "Portugués (Brasil)": "pt-BR",
    "Portugués (Portugal)": "pt-PT",
    "Rumano (Rumanía)": "ro-RO",
    "Ruso (Rusia)": "ru-RU",
    "Eslovaco (Eslovaquia)": "sk-SK",
    "Esloveno (Eslovenia)": "sl-SI",
    "Serbio (Cirílico, Serbia)": "sr-Cyrl-RS",
    "Serbio (Serbia)": "sr-RS",
    "Sueco (Suecia)": "sv-SE",
    "Tailandés (Tailandia)": "th-TH",
    "Turco (Turquía)": "tr-TR",
    "Ucraniano (Ucrania)": "uk-UA",
    "Vietnamita (Vietnam)": "vi-VN",
    "Chino (Simplificado)": "zh-CN",
    "Chino (Tradicional)": "zh-TW"
}
